# -*- coding: utf-8 -*-
"""webscrping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iX8Ts0dSnCaAFXytfsaCwfXRYAMlr8-n
"""

import pandas as pd
import requests
from bs4  import BeautifulSoup

requests.get('https://www.ambitionbox.com/list-of-companies?page=1')

webpage = requests.get('https://books.toscrape.com/catalogue/page-2.html').text
webpage

headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
requests.get('https://www.ambitionbox.com/list-of-companies?page=1',headers=headers).text

soup = BeautifulSoup(webpage, 'lxml')

print(soup.prettify())

soup.find_all('h3')

soup.find_all('h1')

soup.find_all('p')

soup.find_all('h3')[1]

soup.find_all('h3')[2].text

## Scrapping Books Name

for i in soup.find_all('h3'):
  print(i.text)

book_price = []
for i in soup.find_all('p',class_='price_color'):
  book_price.append(i.text.strip())

book_price

availability = []

for i in soup.find_all('p', class_='instock availability'):
  availability.append(i.text.strip())

availability

soup.find_all('img',class_='thumbnail')[4]['src']

image_link = []

for i in soup.find_all('img',class_='thumbnail'):
  image_link.append(i['src'])

image_link

book_name = []
for i in soup.find_all('h3'):
  book_name.append(i.text)

book_name

d = {
    'Book_Name':book_name,
    'Book_Price':book_price,
    'Book_Availability':availability,
    'Book_Image_Link':image_link
}

df = pd.DataFrame(d)

df